---
title: "Lecture_9"
author: "Howard Wang"
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Input
```{r}
wisc.df <- read.csv("WisconsinCancer.csv")
x <- table(wisc.df$diagnosis)
wisc.data <- as.matrix(wisc.df[,3:32])
```

Here we examine data from `r nrow(wisc.df)` patients samples

In this data-set we have `r x["B"]` cancer and `r x["M"]` non-cancer

How many variables/features in the data are suffixed with _mean?

```{r}
length(grep("_mean", colnames(wisc.df)))
```

```{r}
round(apply(wisc.data, 2, sd))
```

```{r}
wisc.pr <- prcomp(wisc.data, scale = T)
summary(wisc.pr)

pca.var <- wisc.pr$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
barplot(pca.var.per, main="Scree Plot",
xlab="Principal Component", ylab="Percent Variation")

par(mar=c(10, 3, 0.35, 0))
barplot(wisc.pr$rotation[,1], las=2 )

plot(wisc.pr$x[,1:2], col=wisc.df$diagnosis)
```

```{r}
x <- summary(wisc.pr)
x$importance[,"PC1"]
```
The first PC captures `r x$importance[2,"PC1"]*100` variance in the data

#How many principal components (PCs) are required to describe at least 70% of the original variance in the data? 

```{r}
which(x$importance[3,]>0.7)[1]
```

```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(wisc.pr$x[,1:3])
wisc.hclust <- hclust(data.dist)
plot(wisc.hclust)
```

```{r}
#url <- "new_samples.csv"
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc
plot(wisc.pr$x[,1:2], col=wisc.df$diagnosis)
points(npc[,1], npc[,2], col="blue", pch=16, cex=3)
text(npc[,1], npc[,2], c(1,2), col="white")
```







